language: php
php:
    - 5.5
    - 5.4
    - 5.3

env:
    - IMAGEMAGICK_VERSION=dev
    - IMAGEMAGICK_VERSION=6.8.7-0
    - IMAGEMAGICK_VERSION=6.7.5-3
    - IMAGEMAGICK_VERSION=6.6.0-9
    - IMAGEMAGICK_VERSION=6.5.3-10
    - IMAGEMAGICK_VERSION=6.4.0-11
    - IMAGEMAGICK_VERSION=6.3.4-10
    - IMAGEMAGICK_VERSION=6.2.3-6

before_script:
    - sudo apt-get update
    - sudo apt-get dist-upgrade -y
    - ./imagemagick_dependency.sh "${IMAGEMAGICK_VERSION}"

script:
    - export NO_INTERACTION=1
    - export REPORT_EXIT_STATUS=1
    - export TEST_PHP_EXECUTABLE=`which php`
    - phpize
    - ./configure --with-imagick="${HOME}/imagemagick-${IMAGEMAGICK_VERSION}" --enable-imagick-zend-mm
    - make
    - php run-tests.php -d extension=imagick.so -d extension_dir=modules -n ./tests/*.phpt
    - for i in `ls tests/*.out 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo ""; echo "-- END"; done
    - make clean
    - ./configure --with-imagick="${HOME}/imagemagick-${IMAGEMAGICK_VERSION}"
    - make
    - php run-tests.php -d extension=imagick.so -d extension_dir=modules -n ./tests/*.phpt
    - for i in `ls tests/*.out 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done

