language: php
php:
    - 7
    - 5.6
    - 5.5
    - 5.4
    - 5.3

matrix:
  allow_failures:
    - env: IMAGEMAGICK_VERSION=git6
    - env: IMAGEMAGICK_VERSION=git7

env:
    - IMAGEMAGICK_VERSION=git7
    - IMAGEMAGICK_VERSION=git6
    - IMAGEMAGICK_VERSION=dev
    - IMAGEMAGICK_VERSION=6.8.7-0
    - IMAGEMAGICK_VERSION=6.7.5-3
    - IMAGEMAGICK_VERSION=6.6.0-9
    - IMAGEMAGICK_VERSION=6.5.3-10
    - IMAGEMAGICK_VERSION=6.4.0-11
    - IMAGEMAGICK_VERSION=6.3.4-10
    - IMAGEMAGICK_VERSION=6.2.3-6

before_script:
    - sudo add-apt-repository ppa:dns/gnu --yes
    - sudo apt-get update -q
    - sudo apt-get install --only-upgrade autoconf
    - for file in tests/*.phpt; do grep $(basename $file) package.xml >/dev/null || (echo "Missing $file from package.xml" ; exit 1); done
    - ./imagemagick_dependency.sh "${IMAGEMAGICK_VERSION}"

script:
    - export NO_INTERACTION=1
    - export REPORT_EXIT_STATUS=1
    - export TEST_PHP_EXECUTABLE=`which php`
    - export PHP_IMAGICK_VERSION=$(php -r '$sxe = simplexml_load_file ("package.xml"); echo (string) $sxe->version->release;')
    - pear package
    - . ./configure-cflags.sh
    - mkdir /tmp/php-imagick-build
    - tar xfz "imagick-${PHP_IMAGICK_VERSION}.tgz" -C /tmp/php-imagick-build
    - cp ./check-loaded.phpt /tmp/php-imagick-build/imagick-${PHP_IMAGICK_VERSION}/check-loaded.phpt
    - cd /tmp/php-imagick-build/imagick-${PHP_IMAGICK_VERSION}
    - phpize
    - ./configure --with-imagick="${HOME}/imagemagick-${IMAGEMAGICK_VERSION}"
    - make
    - php run-tests.php -d extension=imagick.so -d extension_dir=modules -n ./*.phpt
    - php run-tests.php -d extension=imagick.so -d extension_dir=modules -n ./tests/*.phpt
    - for i in `ls tests/*.out 2>/dev/null`; do echo "-- START ${i}"; cat $i; echo "-- END"; done

